name: Delete Post
on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the file to delete'
        required: true
      commit_message:
        description: 'Commit message'
        required: true

jobs:
  delete-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Delete file
        run: |
          rm "${{ github.event.inputs.file_path }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "${{ github.event.inputs.commit_message }}"
          git push
