name: Delete Post

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: ‘Path to the file to delete’
        required: true
      commit_message:
        description: ‘Commit message’
        required: true

jobs:
  delete-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to avoid detached head
          ref: main

      - name: Delete specified file
        run: |
          if [ -f “${{ github.event.inputs.file_path }}” ]; then
            rm “${{ github.event.inputs.file_path }}”
            git config —local user.email “action@github.com”
            git config —local user.name “GitHub Action”
            git add .
            git commit -m “${{ github.event.inputs.commit_message }}”
            git push origin main
            echo “File deleted and changes pushed successfully.”
          else
            echo “File not found: ${{ github.event.inputs.file_path }}”
            exit 1
          fi
