name: Trigger Workflow

on:
  workflow_dispatch:
  
jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    name: Dispatch Event
    steps:
      - name: Trigger target workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"event_type":"trigger-jekyll", "client_payload": {"message": "Triggered from main workflow"}}'
          https://api.github.com/repos/${{ github.repository }}/dispatches
