name: Dispatch Workflow

on:
  workflow_dispatch:

jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: ib-bsb-br/ib-bsb-br.github.io
          event-type: trigger-jekyll
          client-payload: '{"ref": "main"}'
