name: Trigger Workflow
permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      some_input:
        description: 'An example input'
        required: false

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    name: Dispatch Event
    steps:
      - name: Trigger target workflow
        env:
          WORKFLOW_DISPATCH_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $WORKFLOW_DISPATCH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"event_type":"trigger-jekyll", "client_payload": {"message": "Triggered from main workflow"}}' \
            https://api.github.com/repos/ib-bsb-br/ib-bsb-br.github.io/dispatches
