name: Dispatch Workflow

on:
  workflow_dispatch:

jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch GitHub Actions Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"event_type":"trigger-jekyll", "client_payload": {"message": "Triggered from main workflow"}}' \
            https://api.github.com/repos/ib-bsb-br/ib-bsb-br.github.io/dispatches
