name: Build, Deploy, and Add Posts to Spaced Inbox

on:
  push:
    branches: ["main"]
  repository_dispatch:
    types: [trigger-jekyll]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.cache-pip.outputs.cache-hit != 'true'

      - name: Install requests icalendar datetime pyyaml (always run)
        run: pip install requests icalendar datetime pyyaml

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3

      - name: Cache tag data
        uses: actions/cache@v4
        id: cache-tag-data
        with:
          path: ${{ github.workspace }}/.jekyll-cache
          key: tag-data-${{ github.sha }}
          restore-keys: |
            tag-data-

      - name: Cache Jekyll _site directory
        uses: actions/cache@v4
        id: cache-jekyll-site
        with:
          path: ${{ github.workspace }}/_site
          key: jekyll-site-${{ github.sha }}
          restore-keys: |
            jekyll-site-

      - name: Process markdown files for tags
        run: python tags.py

      - name: Fetch calendar events
        run: python events.py

      - name: Commit and push changes (pre-build)
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git diff-index --quiet HEAD || git commit -m "Update content [skip ci]"
          git push origin main || echo "No changes to push"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        env:
          PAGES_REPO_NWO: ib-bsb-br/ib-bsb-br.github.io
          JEKYLL_ENV: production
          base_path: ""
        run: |
          bundle exec jekyll build --trace --config _config.yml --baseurl "${base_path}"

      - name: Generate Pagefind Index
        run: npx -y pagefind --site ${{ github.workspace }}/_site --output-path ${{ github.workspace }}/_site/pagefind

      - name: Modify Pagefind UI
        run: python modify-pagefind-ui.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/_site
          publish_branch: gh-pages
          cname: ib.bsb.br
          allow_empty_commit: true
          enable_jekyll: false
          keep_files: true

  add-posts-to-inbox:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Python dependencies
        uses: actions/cache@v4
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar datetime pyyaml
        if: steps.cache-pip.outputs.cache-hit != 'true'

      - name: Initialize spaced-inbox database
        run: |
          if [ ! -f data.db ]; then
            sqlite3 data.db < schema.sql
          fi

      - name: Extract post URLs
        id: extract-urls
        run: |
          BASE_URL="ib.bsb.br"
          POST_FILES=$(git diff --name-only HEAD^ HEAD -- '_posts/**.md')
          POST_URLS=""
          for POST in $POST_FILES; do
            FILENAME=$(basename "$POST" .md)
            SLUG=$(echo "$FILENAME" | sed 's/^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-//')
            POST_URL="$BASE_URL/$SLUG/"
            POST_URLS="$POST_URLS\n$POST_URL"
          done
          echo -e "$POST_URLS" > post_urls.txt

      - name: Append URLs to inbox file
        run: |
          if [ -s post_urls.txt ]; then
            while read -r URL; do
              echo -e "\n$URL\n=====" >> infoBAG.txt
            done < post_urls.txt
          fi

      - name: Install matplotlib
        run: pip install matplotlib          

      - name: Run spaced inbox script
        run: python script.py --no-review
        env:
          TERM: xterm

      - name: Run review load visualizer
        run: python review_load.py data.db
        
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git diff-index --quiet HEAD || git commit -m "Update spaced-inbox with new posts"
          git pull --rebase
          git push
